language: ruby
rvm: 2.3.7
sudo: false
matrix:
  include:
    - rvm: 2.3.7
    - rvm: 2.4.4
    - rvm: 2.5.1
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

os:
  - linux

env:
  - RUBYOPT="--enable-frozen-string-literal"
  - RUBYOPT=""

before_install:
  - gem install bundler

script:
  - gem list -l
  - bundle exec rake compile
  - bundle exec rake
  - bundle exec codeclimate-test-reporter
  - gem build ./midori.gemspec

bundler_args: --jobs 1 --retry 3

notifications:
  email: false
